name: Auth Service CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        run: az acr login --name devopsacr30179

      - name: Build Docker image
        run: |
          docker build \
            -t devopsacr30179.azurecr.io/auth-service:${{ github.sha }} \
            ./phase1/auth-service

      - name: Push Docker image
        run: |
          docker push devopsacr30179.azurecr.io/auth-service:${{ github.sha }}
      # ðŸ”½ CD STARTS HERE (Phase 4 â€“ Day 3)
      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: devops-rg
          cluster-name: devops-aks

      - name: Deploy auth-service to AKS
        run: |
          kubectl set image deployment/auth-deployment \
            auth=${{ secrets.ACR_LOGIN_SERVER }}/auth-service:${{ github.sha }} \
            -n devops

          kubectl rollout status deployment/auth-deployment -n devops
  